### ISSUE TITLE
Not bower installable?

### ISSUE THREAD

**Issue by philrenaud** [syntax-tree/nlcst-search#1]
Noticed that unist-util-visit was coming back with ENOTFOUND on bower install of nlcst-search:

```
bower install https://github.com/wooorm/nlcst-search.git

bower nlcst-search#*            cached https://github.com/wooorm/nlcst-search.git#1.1.1
bower nlcst-search#*          validate 1.1.1 against https://github.com/wooorm/nlcst-search.git#*
bower                        ENOTFOUND Package wooorm/unist-util-visit=wooorm/unist-util-visit not found
```

**Comment by wooorm** [comment]
Yup, you caught me! :)

I’m currently in the process of removing `bower.json` files for my repositories because there is nearly no interest in it (you’re the first in half a year with a question regarding Bower) and it is a hassle to keep maintaining two (three, as I’m also removing `duo` with `component.json` files) manifests.

The reason this currently fails is because there’s still a `component.json` file in this repo, which, as you might know, was the previous name of `bower.json`.

I suggest to use `nlcst-search` (and my other tools) through browserify or webpack instead!

**Comment by philrenaud** [comment]
All good; using it in an Ember/Ember-CLI context to using their static import method. Thanks very much!

**Comment by wooorm** [comment]
:ok_hand:
